"""set restaurant foreign key to null on delete

Revision ID: f36703a09702
Revises: 61bf3bf82069
Create Date: 2026-09-24 13:59:27.594169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f36703a09702'
down_revision: Union[str, Sequence[str], None] = '61bf3bf82069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_restaurant_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'restaurants', ['restaurant_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_restaurant_id_fkey'), 'users', 'restaurants', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###
